### ISSUE TITLE
Implement option for multiple audios instead of just one

### ISSUE THREAD

**Issue by crashzk** [Sarrus1/----ZonesAntiCamp#1]
It would be interesting to put the anticamp folder and all the audios in there instead of just one audio from the folder, so we can place several audios and always play a different one for when the player is going to camper.

**Comment by Sarrus1** [comment]
Hey, good idea!

Will try to implement that!

**Comment by Sarrus1** [comment]
Added in 34406dc63e659b6376c4ef891689ee80c9c5b41f
