### ISSUE TITLE
Implement option to stop playing the sound when the player leaves the anticamp zone

### ISSUE THREAD

**Issue by crashzk** [Sarrus1/----ZonesAntiCamp#7]
Implement option to stop playing the sound when the player leaves the anticamp zone.

I haven't tested it in depth with 2 second soft sounds yet, but I believe it would be good to say that when the player is no longer in the zone considered for the anticamp, the sound stops playing, even without having finished.

I will currently be testing sounds longer than 7 seconds to see how it works, stop playing alone when the player leaves the anticamp zone.

**Comment by Sarrus1** [comment]
Added in a3a273e9482cd1d146316be9fae0e65cf46f0646
